services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library-management-db:5432/library-management-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      library-management-db:
        condition: service_healthy
    networks:
      - spring-postgres

  library-management-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=library-management-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    networks:
      - spring-postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d library-management-db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  spring-postgres: