spring:
  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/library-management-db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
